version: '3.1'

services:
  backend:
    depends_on:
      - mongo
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/
      - DB_NAME=Mood
      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 

  
  celery:
      container_name: celery_worker
      depends_on:
       - redis
      build:
        context: .
        dockerfile: CeleryDockerfile
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - CELERY_IMPORTS=utils.Email
        - MONGO_URL=mongodb://root:example@mongo:27017/
        - DB_NAME=Mood



  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false