version: '3.1'

services:
  backend:
    depends_on:
      - mongo
    build:
      context: ./src
      dockerfile: Dockerfile

    ports:
      - 8080:8080
    env_file:
      - docker-compose.env

      
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - docker-compose.env


  
  celery:
      container_name: celery_worker
      depends_on:
       - redis
      build:
        context: ./src
        dockerfile: CeleryDockerfile
      env_file:
        - docker-compose.env

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - docker-compose.env
